name: RadioTimeKit CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme RadioTimeKit -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme RadioTimeKit -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
    - name: Build for macOS
      run: swift build
    - name: Run macOS tests
      run: swift test
